v

services:
  backend:
    build: ./backend
    container_name: cenate-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://10.0.89.13:5432/maestro_cenate
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Essalud2025
    ports:
      - "8080:8080"
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://cenate-backend:8080/api
    container_name: cenate-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
