-- ============================================================================
-- Script: V3_0_3__crear_tabla_estados_gestion_citas.sql
-- Descripción: Crear tabla de Estados para Gestión de Citas
-- Fecha: 2026-01-22
-- Versión: v1.33.0
-- ============================================================================

-- Crear tabla dim_estados_gestion_citas
CREATE TABLE IF NOT EXISTS public.dim_estados_gestion_citas (
    id_estado_cita BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_estado_cita TEXT NOT NULL UNIQUE,
    desc_estado_cita TEXT NOT NULL,
    stat_estado_cita TEXT NOT NULL DEFAULT 'A',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dim_estados_gestion_citas_stat_check
        CHECK (stat_estado_cita = ANY (ARRAY['A'::text, 'I'::text]))
);

-- Crear índices
CREATE INDEX IF NOT EXISTS idx_estados_gestion_citas_cod
    ON public.dim_estados_gestion_citas(cod_estado_cita);

CREATE INDEX IF NOT EXISTS idx_estados_gestion_citas_stat
    ON public.dim_estados_gestion_citas(stat_estado_cita);

CREATE INDEX IF NOT EXISTS idx_estados_gestion_citas_desc_tsvector
    ON public.dim_estados_gestion_citas
    USING gin(to_tsvector('spanish'::regconfig, desc_estado_cita));

-- Crear función para actualizar updated_at
CREATE OR REPLACE FUNCTION _touch_estado_gestion_cita()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Crear trigger para actualizar updated_at
DROP TRIGGER IF EXISTS trg_touch_estado_gestion_cita ON public.dim_estados_gestion_citas;
CREATE TRIGGER trg_touch_estado_gestion_cita
BEFORE UPDATE ON public.dim_estados_gestion_citas
FOR EACH ROW
EXECUTE FUNCTION _touch_estado_gestion_cita();

-- Comentarios de documentación
COMMENT ON TABLE public.dim_estados_gestion_citas
    IS 'Tabla de estados para gestión de citas de pacientes';

COMMENT ON COLUMN public.dim_estados_gestion_citas.id_estado_cita
    IS 'Identificador único del estado de cita';

COMMENT ON COLUMN public.dim_estados_gestion_citas.cod_estado_cita
    IS 'Código único del estado (ej: CITADO, NO_CONTESTA)';

COMMENT ON COLUMN public.dim_estados_gestion_citas.desc_estado_cita
    IS 'Descripción detallada del estado de la cita';

COMMENT ON COLUMN public.dim_estados_gestion_citas.stat_estado_cita
    IS 'Estado del registro: A=Activo, I=Inactivo';

COMMENT ON COLUMN public.dim_estados_gestion_citas.created_at
    IS 'Fecha de creación del registro (auto-generada)';

COMMENT ON COLUMN public.dim_estados_gestion_citas.updated_at
    IS 'Fecha de última actualización (auto-actualizada)';

-- Insertar 10 Estados Iniciales
INSERT INTO public.dim_estados_gestion_citas (cod_estado_cita, desc_estado_cita, stat_estado_cita)
VALUES
    ('CITADO', 'Citado - Paciente agendado para atención', 'A'),
    ('ATENDIDO_IPRESS', 'Atendido por IPRESS - Paciente recibió atención en institución', 'A'),
    ('NO_CONTESTA', 'No contesta - Paciente no responde a las llamadas', 'A'),
    ('SIN_VIGENCIA', 'Sin vigencia de Seguro - Seguro del paciente no vigente', 'A'),
    ('APAGADO', 'Apagado - Teléfono del paciente apagado', 'A'),
    ('NO_DESEA', 'No desea - Paciente rechaza la atención', 'A'),
    ('REPROG_FALLIDA', 'Reprogramación Fallida - No se pudo reprogramar la cita', 'A'),
    ('NUM_NO_EXISTE', 'Número no existe - Teléfono registrado no existe', 'A'),
    ('HC_BLOQUEADA', 'Historia clínica bloqueada - HC del paciente bloqueada en sistema', 'A'),
    ('TEL_SIN_SERVICIO', 'Teléfono sin servicio - Línea telefónica sin servicio', 'A')
ON CONFLICT (cod_estado_cita) DO NOTHING;
