-- =====================================================================
-- 📋 Creación de tabla dim_tipos_bolsas para administración de tipos de bolsas
-- v1.0.0 - Gestión centralizada de categorías de bolsas
-- =====================================================================

-- Crear tabla de tipos de bolsas
CREATE TABLE IF NOT EXISTS public.dim_tipos_bolsas (
    id_tipo_bolsa BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cod_tipo_bolsa TEXT NOT NULL UNIQUE,
    desc_tipo_bolsa TEXT NOT NULL,
    stat_tipo_bolsa TEXT NOT NULL DEFAULT 'A',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dim_tipos_bolsas_stat_check CHECK (stat_tipo_bolsa = ANY (ARRAY['A'::text, 'I'::text]))
);

-- Crear índices para optimización de búsquedas
CREATE INDEX IF NOT EXISTS idx_tipos_bolsas_cod ON public.dim_tipos_bolsas(cod_tipo_bolsa);
CREATE INDEX IF NOT EXISTS idx_tipos_bolsas_stat ON public.dim_tipos_bolsas(stat_tipo_bolsa);
CREATE INDEX IF NOT EXISTS idx_tipos_bolsas_desc_tsvector ON public.dim_tipos_bolsas USING gin(to_tsvector('spanish'::regconfig, desc_tipo_bolsa));

-- Crear función para actualizar updated_at automáticamente
CREATE OR REPLACE FUNCTION _touch_tipo_bolsa()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Crear trigger para actualizar timestamp
DROP TRIGGER IF EXISTS trg_touch_tipo_bolsa ON public.dim_tipos_bolsas;
CREATE TRIGGER trg_touch_tipo_bolsa
BEFORE UPDATE ON public.dim_tipos_bolsas
FOR EACH ROW
EXECUTE FUNCTION _touch_tipo_bolsa();

-- Insertar tipos de bolsas iniciales basados en los datos existentes
INSERT INTO public.dim_tipos_bolsas (cod_tipo_bolsa, desc_tipo_bolsa, stat_tipo_bolsa)
VALUES
    ('BOLSA_107', 'Bolsa 107 - Importación de pacientes masiva', 'A'),
    ('BOLSA_DENGUE', 'Bolsa Dengue - Control epidemiológico', 'A'),
    ('BOLSAS_ENFERMERIA', 'Bolsas Enfermería - Atenciones de enfermería', 'A'),
    ('BOLSAS_EXPLOTADATOS', 'Bolsas Explotación de Datos - Análisis y reportes', 'A'),
    ('BOLSAS_IVR', 'Bolsas IVR - Sistema interactivo de respuesta de voz', 'A'),
    ('BOLSAS_REPROGRAMACION', 'Bolsas Reprogramación - Citas reprogramadas', 'A'),
    ('BOLSA_GESTORES_TERRITORIAL', 'Bolsa Gestores Territorial - Gestión territorial', 'A')
ON CONFLICT (cod_tipo_bolsa) DO NOTHING;

-- Comentarios de tabla para documentación
COMMENT ON TABLE public.dim_tipos_bolsas IS 'Tabla de categorías/tipos de bolsas de pacientes para el módulo de Bolsas';
COMMENT ON COLUMN public.dim_tipos_bolsas.id_tipo_bolsa IS 'Identificador único de tipo de bolsa';
COMMENT ON COLUMN public.dim_tipos_bolsas.cod_tipo_bolsa IS 'Código único del tipo de bolsa (ej: BOLSA_107)';
COMMENT ON COLUMN public.dim_tipos_bolsas.desc_tipo_bolsa IS 'Descripción detallada del tipo de bolsa';
COMMENT ON COLUMN public.dim_tipos_bolsas.stat_tipo_bolsa IS 'Estado: A=Activo, I=Inactivo';
COMMENT ON COLUMN public.dim_tipos_bolsas.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN public.dim_tipos_bolsas.updated_at IS 'Fecha de última actualización';
