// src/constants/auth.js
export const ROLES = {
    MEDICO: "MEDICO",
    COORDINADOR_MEDICO: "COORDINADOR_MEDICO",
    EXTERNO: "EXTERNO",
    CITAS: "CITAS",
    COORD_LINEAMIENTOS_IPRESS: "COORD_LINEAMIENTOS_IPRESS", // 👈 nuevo
};

export const PERMISOS = {
    // Lineamientos IPRESS
    VER_LINEAMIENTOS: "VER_LINEAMIENTOS",
    EDITAR_LINEAMIENTOS: "EDITAR_LINEAMIENTOS",
    APROBAR_LINEAMIENTOS: "APROBAR_LINEAMIENTOS",
};
