spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/maestro_cenate}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:chatuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:chatpass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.address=0.0.0.0
server.port=8080
